[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "npyosmium"
description = "Python bindings for libosmium, the data processing library for OSM data, with numpy interface"
readme = "README.rst"
requires-python = ">=3.8"
license = {text = 'BSD-2-Clause'}
authors = [
    {name = "Sarah Hoffmann", email = "lonvia@denofr.de"}
    ]
maintainers = [
    {name = "Aurélien Grenotton", email = "agrenott@gmail.com"}
    ]
keywords = ["OSM", "OpenStreetMap", "Osmium"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C++",
    ]
dependencies = [
    "requests"
    ]

dynamic = ["version"]

[tool.setuptools]
packages = [
    "npyosmium",
    "npyosmium.osm",
    "npyosmium.replication"
    ]
package-dir = {"" = "src"}


[project.urls]
Homepage = "https://github.com/agrenott/npyosmium"
# Documentation = "https://docs.osmcode.org/pyosmium/latest/"
Repository = "https://github.com/agrenott/npyosmium"
Issues = "https://github.com/agrenott/npyosmium/issues"

[project.optional-dependencies]
tests = [
    'pytest',
    'pytest-httpserver',
    'werkzeug',
    'shapely'
    ]
docs = [
    'mkdocs',
    'mkdocs-material',
    'mkdocstrings',
    'mkdocstrings-python',
    'mkdocs-autorefs',
    'mkdocs-gen-files',
    'mkdocs-jupyter',
    'argparse-manpage '
    ]

[tool.setuptools.dynamic]
version = {attr = "npyosmium.version.npyosmium_release"}
