[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=2.9"]
build-backend = "scikit_build_core.build"

[project]
name = "npyosmium"
version = "4.3.1"
description = "Python bindings for libosmium, the data processing library for OSM data, with numpy interface"
requires-python = ">=3.9"
readme = "README.md"
license = {text = 'BSD-2-Clause'}
authors = [
    {name = "Sarah Hoffmann", email = "lonvia@denofr.de"}
    ]
maintainers = [
    {name = "Aurélien Grenotton", email = "agrenott@gmail.com"}
    ]
keywords = ["OSM", "OpenStreetMap", "Osmium"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 2 - Beta",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C++",
    "Typing :: Typed"
    ]
dependencies = [
    "requests"
    ]

[project.urls]
Homepage = "https://github.com/agrenott/npyosmium"
# Documentation = "https://docs.osmcode.org/pyosmium/latest/"
Repository = "https://github.com/agrenott/npyosmium"
Issues = "https://github.com/agrenott/npyosmium/issues"

[project.optional-dependencies]
tests = [
    'pytest',
    'pytest-httpserver',
    'pytest-run-parallel',
    'werkzeug',
    'shapely'
    ]
docs = [
    'mkdocs',
    'mkdocs-material',
    'mkdocstrings',
    'mkdocstrings-python',
    'mkdocs-autorefs',
    'mkdocs-gen-files',
    'mkdocs-jupyter',
    'argparse-manpage'
    ]

[project.scripts]
pyosmium-get-changes = "npyosmium.tools.pyosmium_get_changes:main"
pyosmium-up-to-date = "npyosmium.tools.pyosmium_up_to_date:main"

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.version = ">=3.15"
# build.verbose = true
# logging.level = "DEBUG"

[tool.scikit-build.sdist]
cmake = true
exclude = ['**']
include = ['/src/**/*.py',
           '/src/**/*.pyi',
           '/src/npyosmium/py.typed',
           '/test/**/*.py',
           '/lib/**/*.cc',
           '/lib/**/*.h',
           '/cmake/*',
           '/docs/*.md',
           '/docs/*/*.md',
           '/docs/*/*.css',
           '/docs/cookbooks/*ipynb',
           '/docs/Makefile',
           '/examples/*py',
           '/mkdocs.yaml',
           '/pyproject.toml',
           '/README.*',
           '/CHANGELOG.md',
           '/CMakeLists.txt',
           '/LICENSE.TXT',
           '/contrib/libosmium/include',
           '/contrib/libosmium/CMakeLists.txt',
           '/contrib/libosmium/LICENSE',
           '/contrib/libosmium/README.md',
           '/contrib/protozero/include',
           '/contrib/protozero/CMakeLists.txt',
           '/contrib/protozero/LICENSE',
           '/contrib/protozero/README.md',
           ]

[tool.pytest]
log_cli = false
markers = ["thread_unsafe: marks tests that are not thread safe","iterations(1): number of iterations for the test"]
