name: 'Fetch dependencies'
description: 'Fetch dependencies from github into "contrib" folder'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: pybind/pybind11
        ref: v2.11.1
        path: contrib/pybind11

    - uses: actions/checkout@v4
      with:
        repository: mapbox/protozero
        ref: v1.7.1
        path: contrib/protozero

    - uses: actions/checkout@v4
      with:
        repository: osmcode/libosmium
        ref: v2.20.0
        path: contrib/libosmium
