name: Build wheels

on:
  push:
    branches:
      - npyosmium
  pull_request:
  release:
    types: [published]

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/fetch_deps

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.cibw_build }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13, macos-14]
        cibw_build: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
        include:
          - os: macos-13
            deployment_target: "10.13" # minimal version required by libosmium
        exclude:
          - os: macos-14
            cibw_build: "cp38-*"

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/fetch_deps

      - uses: mad9000/actions-find-and-replace-string@5
        # Escaping '*'...
        id: articafact_name
        with:
          source: cibw-wheels-${{ matrix.os }}-${{ matrix.cibw_build }}
          find: '*'
          replace: '_'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
           CIBW_ARCHS: native
           CIBW_BUILD: ${{ matrix.cibw_build }}
           # Disable python 3.7 due to https://github.com/pypa/manylinux/pull/1532
           CIBW_SKIP: "pp* *musllinux* cp37-*"
           CIBW_TEST_REQUIRES: pytest pytest-httpserver shapely
           CIBW_TEST_REQUIRES_LINUX: urllib3<2.0 pytest pytest-httpserver shapely
           CIBW_TEST_COMMAND: pytest {project}/test
           CIBW_BUILD_FRONTEND: build
           CIBW_BEFORE_BUILD_LINUX: yum install -y sparsehash-devel expat-devel boost-devel zlib-devel bzip2-devel lz4-devel
           CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=${{ matrix.deployment_target || '10.9' }}"
           # Can't use system/brew lz4 as they do not honor MACOSX_DEPLOYMENT_TARGET 
           # See https://cibuildwheel.pypa.io/en/stable/faq/#missing-dependencies
           CIBW_BEFORE_BUILD_MACOS: brew install boost google-sparsehash; brew uninstall --ignore-dependencies lz4; wget https://github.com/lz4/lz4/releases/download/v1.10.0/lz4-1.10.0.tar.gz; tar xvfz lz4-1.10.0.tar.gz; cd lz4-1.10.0; make; sudo make install
           CIBW_BEFORE_BUILD_WINDOWS: vcpkg install bzip2:x64-windows expat:x64-windows zlib:x64-windows boost-variant:x64-windows boost-iterator:x64-windows lz4:x86-windows
           CIBW_ENVIRONMENT_WINDOWS: 'CMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.articafact_name.outputs.value }}
          path: ./wheelhouse/*.whl

  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'  # only publish to PyPI on github release publication
    runs-on: ubuntu-latest
    needs: 
      - make_sdist
      - build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/npyosmium
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
