name: Build wheels

on:
  push:
    branches:
      - npyosmium
  pull_request:
  release:
    types: [published]

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # we don't want submodules of libosmium

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.cibw_build }} wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13, macos-14]
        arch: [native]
        cibw_build: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
        include:
          - os: macos-13
            deployment_target: "10.13" # minimal version required by libosmium
          - os: ubuntu-20.04
            arch: aarch64
        exclude:
          - os: macos-14
            cibw_build: "cp38-*"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # we don't want submodules of libosmium

      - uses: mad9000/actions-find-and-replace-string@5
        # Escaping '*'...
        id: articafact_name
        with:
          source: cibw-wheels-${{ matrix.os }}-${{ matrix.cibw_build }}-${{ matrix.arch }}
          find: '*'
          replace: '_'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ matrix.arch == 'aarch64' }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' #TODO: is this needed?

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        env:
           CIBW_ARCHS: native
           CIBW_BUILD: ${{ matrix.cibw_build }}
           # Disable python 3.7 due to https://github.com/pypa/manylinux/pull/1532
           CIBW_SKIP: "pp* *musllinux* cp37-* cp38-*linux_aarch64"
           CIBW_TEST_REQUIRES: pytest pytest-httpserver shapely
           CIBW_TEST_REQUIRES_LINUX: urllib3<2.0 pytest pytest-httpserver shapely
           CIBW_TEST_COMMAND: pytest {project}/test
           CIBW_BUILD_FRONTEND: build
           CIBW_BEFORE_BUILD_LINUX: yum install -y expat-devel boost-devel zlib-devel bzip2-devel lz4-devel
           CIBW_BEFORE_BUILD_MACOS: brew install boost
           CIBW_BEFORE_BUILD_WINDOWS: vcpkg install bzip2:x64-windows expat:x64-windows zlib:x64-windows boost-variant:x64-windows boost-iterator:x64-windows lz4:x86-windows
           CIBW_ENVIRONMENT_WINDOWS: 'CMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"'
           CIBW_ENVIRONMENT_MACOS: CMAKE_WITH_LZ4=OFF MACOSX_DEPLOYMENT_TARGET=11.0

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.articafact_name.outputs.value }}
          path: ./wheelhouse/*.whl

  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'  # only publish to PyPI on github release publication
    runs-on: ubuntu-latest
    needs: 
      - make_sdist
      - build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/npyosmium
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
