name: Build wheels

on:
  push:
    branches:
      - npyosmium
  pull_request:
  release:
    types: [published]

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install python to get devel headers
      - uses: actions/setup-python@v5
        id: cp313
        with:
          python-version: '3.13'

      - name: Build SDist
        run: pipx run --python '${{ steps.cp313.outputs.python-path }}' build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.cibw_build }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
        vcpkg: [none]
        cibw_build: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
        include:
         - os: windows-latest
           vcpkg: 'C:/vcpkg/installed/x64-windows'
         - os: windows-11-arm
           vcpkg: 'C:/vcpkg/installed/arm64-windows'

    steps:
      - uses: actions/checkout@v4

      - uses: mad9000/actions-find-and-replace-string@5
        # Escaping '*'...
        id: articafact_name
        with:
          source: cibw-wheels-${{ matrix.os }}-${{ matrix.cibw_build }}
          find: '*'
          replace: '_'

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
           CIBW_ENABLE: cpython-freethreading
           CIBW_ARCHS: native
           CIBW_BUILD: ${{ matrix.cibw_build }}
           # Disable python 3.7 due to https://github.com/pypa/manylinux/pull/1532
           CIBW_SKIP: "pp* *musllinux* cp37-* cp38-*linux_aarch64"
           CIBW_TEST_REQUIRES: pytest pytest-httpserver #shapely
          #  CIBW_TEST_REQUIRES_LINUX: urllib3<2.0 pytest pytest-httpserver shapely
           CIBW_TEST_COMMAND: pytest {project}/test
           CIBW_BUILD_FRONTEND: build
           CIBW_BEFORE_BUILD_LINUX: yum install -y expat-devel boost-devel zlib-devel bzip2-devel lz4-devel
           CIBW_BEFORE_BUILD_MACOS: brew install boost
           CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0 SKBUILD_CMAKE_ARGS=-DWITH_LZ4=OFF
           CIBW_BEFORE_BUILD_WINDOWS: vcpkg install bzip2 expat zlib boost-variant boost-iterator lz4
           CIBW_ENVIRONMENT_WINDOWS: 'CMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"'
           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: 'pipx run delvewheel repair --add-path ${{ matrix.vcpkg }}/bin/ --add-path ${{ matrix.vcpkg }}/debug/bin -w {dest_dir} {wheel}'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.articafact_name.outputs.value }}
          path: ./wheelhouse/*.whl

  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'  # only publish to PyPI on github release publication
    runs-on: ubuntu-latest
    needs: 
      - make_sdist
      - build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/npyosmium
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
